test/runtests.jl

Separate pull request because these tests depend on [pull request #679 from DataFrames.jl](https://github.com/JuliaStats/DataFrames.jl/pull/679) (now merged).  Together, these also address #76

tests for prediction using DataFrames with and without response variable

---

REQUIRE
src/GLM.jl
src/glmfit.jl
src/glmtools.jl
src/lm.jl

`df_residual` becomes a method from StatsBase if the following pull request is merged: https://github.com/JuliaStats/StatsBase.jl/pull/120

Import df_residual

---

REQUIRE
perf/glm.jl
src/GLM.jl
src/glmfit.jl
src/glmtools.jl
src/lm.jl

Simplify the code
- Use dispatch instead of functors
- Remove NumericFuns dependency
- Perform updatemu! in a single step, rather than by traversing each individual array

Simplify the code

---

src/glmfit.jl

This is useful for packages that want to extend the GLM code to do something slightly different, e.g. https://github.com/simonster/FirthRegression.jl/blob/master/src/FirthRegression.jl

Introduce AbstractGLM and make GeneralizedLinearModel a subtype

---

test/runtests.jl

To support running tests in `LOAD_PATH`.

Use @__FILE__ instead of Pkg.dir to find the data dir in the test.

---

src/GLM.jl
src/glmfit.jl
src/glmtools.jl
src/linpred.jl
src/lm.jl

- Only a single expression per line
- Spaces around operators
- Line breaks in long lines
- Remove whitespace

Some formatting changes.

---

perf/glm.jl
src/GLM.jl
src/glmfit.jl
src/glmtools.jl
src/linpred.jl
src/lm.jl

Use eachindex(x) instead of 1:length(x) and other cleanup

---

REQUIRE

Needed for fit statistics functions.

Raise requirement on StatsBase

---

src/glmfit.jl

The mutating function `wrkresp!` was accidentally written as a method for `wrkresp`.
This PR also includes a specialized `updateμ!` method for the Gamma distribution and its canonical link `InverseLink`.
The reason for writing the specialized `updateμ!` methods is because terms that may be close to zero cancel in the evaluation of the `wrkresid` for the canonical link.

updateμ! method for Gamma/Inverse, properly name wrkresp!

---

src/linpred.jl
test/runtests.jl

Fixes #153. 
Also remove 0.4 prerelease specific code.

Make cholfact(DensePredQR) inferable

---

src/glmfit.jl
test/runtests.jl

Stop if deviance is zero

---

README.md
doc/index.rst
perf/glm.jl
test/REQUIRE
test/runtests.jl

Introduced in DataFrames 0.9.0, so I've bumped the test requirement on DataFrames.

Update formula syntax from bare tilde to macro

---

REQUIRE
src/GLM.jl
src/linpred.jl

`Cholesky` now has an `info` field and we need to import from `SpecialFunctions`.

Fixes for Julia 0.7

---

src/glmfit.jl
test/runtests.jl

Fixes #224 
Also reorganize some tests and add comments to `_fit!`.

 Use tolerance to decide on step size in line search

---

src/glmfit.jl
test/runtests.jl

Make sure that y is checked before calls to link function such that
useful error message is printed when values are outside the valid domain
Initialize wts and offset vectors as empty vectors when not supplied and
adjust code to consistently handle this.
Fix check for Binomial distribution
Fixes #228 
Diff without white space changes https://github.com/JuliaStats/GLM.jl/pull/229/files?w=1

Define new GlmResp constructor that allocates and initializes μ and η

---

src/lm.jl
test/runtests.jl

See #263 
It also fixes errors due to #201

Fixes bug in dof_residual with allowrankdeficient

---

.travis.yml
README.md
docs/Project.toml
docs/make.jl
docs/src/index.md
src/ftest.jl
src/glmtools.jl

Also remove the PkgEval badge from Readme.md since it's no longer maintained.

Reenable docs deployment and switch to now project based method

---

Project.toml

Update version bounds on dependencies

---

src/glmfit.jl

Seemed to happen sometimes on CI.

Fix "wrkresᵢ not defined" error

---

src/glmfit.jl
src/lm.jl

As people are often confused about this, notably as the R default is different (and poorly documented there too...).

Improve documentation about weights

---

src/glmtools.jl
test/runtests.jl

Make == less strict for links 

---

Project.toml

For a release with the most recent changes.

Bump version to 1.3.10

---

src/lm.jl
test/runtests.jl

Fix deprecation of predict(..., interval=:confint)

---

.github/workflows/CI-future.yml
.github/workflows/CI-stable.yml

I missed this when merging https://github.com/JuliaStats/GLM.jl/pull/434.

Fix GitHub Actions arch

---

Project.toml
src/linpred.jl

cf https://github.com/JuliaStats/StatsModels.jl/pull/226

use StatsModels.formula

---

LICENSE.md

This comes from #441.  Happy to update the language---primarily I just wanted to indicate that there is indeed a GPL dependency here for now. :+1:

Update license to indicate GPL dependency.

---

docs/src/index.md

Preliminary attempt at adding discussion of `residuals` convenience function to docs, since it's in the code (and obviously in StatsBase), but not, as far as I can tell, mentioned otherwise anywhere in any of the docs.

Add residuals convenience function to docs

---

Project.toml
src/linpred.jl
test/runtests.jl

Closes #470, closes #213. 
After working on this, I also discovered @dmbates's [original work](https://github.com/JuliaStats/GLM.jl/commit/27804d0104136a49fb388959c40b4d900f1a31af) on fixing this.

Improved support for views

---

Project.toml
src/glmtools.jl
test/runtests.jl

safer int for binomial loglik

---

Project.toml
src/GLM.jl
src/linpred.jl
test/runtests.jl

will be the immediate release of the fix to #428

backport VIF to 1.x release

---

docs/src/api.md
src/glmfit.jl
src/glmtools.jl
test/runtests.jl

see #591 for details
fixes #591

removed `mueta(::Link)`

---

ext/GLMSparseArraysExt.jl
test/runtests.jl

Add SparsePredQR to fix sparse fitting based on method=:qr
