REQUIRE, perf/glm.jl, src/GLM.jl, src/glmfit.jl, src/glmtools.jl, src/linpred.jl, src/lm.jl
Fixes  #94. The performance on the benchmark in `perf` is very slightly faster (~2%).
This also includes some miscellaneous changes from my working copy:
- Improved type stability
- Ability to specify starting coefficients
- Better handling of steps that result in invalid eta values
- Re-export Distributions instead of bringing it into Main
=> Remove NumericExtensions

src/glmfit.jl, src/glmtools.jl
The `ProbInv` function was not precise for large negative values so using another formula improved precision. In addition, the Bernoulli variance calculation `p*(1-p)` could be improved for all link functions for which it doesn't matter if we set `p=F^{-1}(x'β)` or `p=F^{-1}(-x'β)`. Finally, residual deviation calculations for `Binomial` is made more precise.
I had to comment out the prediction tests because they are running a glm with Bernoulli response on data in the [0,1] interval. Does that makes sense? I haven't seen it before.
@dmbates, @kleinschmidt
=> Fix #99 by improving precision in ProbInv and variance calculations.

src/glmfit.jl, test/runtests.jl
`predict` should allow an offset to be specified. I can't think of a use case where you would want to fit with an offset and predict without, or vice versa, so I am requiring an offset to be specified if the model is fit with one (and vice versa).
Also `StatsBase.predict` for dataframes ([implemented here](https://github.com/JuliaStats/DataFrames.jl/blob/267a69754cb8fed06af4f2bd3475b17d75cf1cfe/src/statsmodels/statsmodel.jl#L68-L75)) currently does not allow additional args. I think changing it to
```julia
function StatsBase.predict(mm::DataFrameRegressionModel, df::AbstractDataFrame, args...; kwargs...)
newTerms = remove_response(mm.mf.terms)
newX = ModelMatrix(ModelFrame(newTerms, df)).m
predict(mm, newX, args...; kwargs...)
end
```
will do the trick.
When this gets merged, I'll open an …
=> Make predict work with offsets

src/lm.jl, test/runtests.jl
=> Allow users to use integer arrays as input (but convert them).

doc/index.rst, src/GLM.jl, src/glmfit.jl, src/glmtools.jl, src/linpred.jl, src/lm.jl, test/REQUIRE, test/runtests.jl
This implements functions to be added to StatsBase (https://github.com/JuliaStats/StatsBase.jl/pull/146): `loglikelihood`, `nullloglikelihood`, `nulldeviance`, `df`. It also adds an `adjR²` function, and changes `nobs` to return the sum of weights where it makes sense. Tests for fitting models using weights are also introduced. Fixes https://github.com/JuliaStats/GLM.jl/issues/74.
Issues to tackle:
To use this, you need https://github.com/JuliaStats/StatsBase.jl/pull/146. Also, after fitting a model from a `DataFrame`, you need to call the functions on `obj.model` rather than on `obj` directly (or to add code to DataFrames.jl to delegate the functions to that object). I'll make a PR to fix that when we have agreed on the API.
(Tests will fail until …
=> Implement fit statistics functions

test/runtests.jl
linreg() now returns a tuple instead of an array.
=> Fix test_approx_eq failure on Julia 0.5

REQUIRE, src/GLM.jl, src/lm.jl, test/REQUIRE, test/runtests.jl
I bumped the StatsBase requirement to 0.8.3, in which `R2`, `adjR2`, `AIC`, `AICc`, and `BIC` have been deprecated in favor of their lowercase equivalents.
=> Update functions deprecated in StatsBase

REQUIRE, src/GLM.jl
These are defined in `StatsFuns` but `StatsBase` is importing and exporting them. Hopefully `StatsBase` will soon not depend on `StatsFuns` anymore so we want to use the right source here.
=> Import from StatsFuns instead of StatsBase

src/glmfit.jl
This has not been updated to reflect the move of weights into loglik_obs().
=> Simplify zero() call in loglikelihood

src/GLM.jl, src/glmfit.jl, src/glmtools.jl, src/lm.jl, test/runtests.jl
- Define methods for `updateμ!` specific to Distribution/Link combinations for the canonical link.
- Having specific methods removes some of the numerical issues in evaluating the working weights.
- Remove the unused parameter `wt` in `devresid` methods.  All calls to these methods were with `wt = 1` and it was used as a multiplier.
- Allow for multithreaded evaluation of `updateμ!` with canonical links.
- Switch tests to use `@testset` and replace calls to `@test_approx_eq a b` to `@test isapprox(a,b)`, allowing for more flexibility in setting `atol` or `rtol`
=> Specialized update methods for canonical links.

REQUIRE, src/GLM.jl, src/glmfit.jl, src/linpred.jl, src/lm.jl, test/REQUIRE, test/runtests.jl
This bumps the StatsBase requirement to 0.11.0, which deprecates `df` in favor of `dof`, and changes all occurrences of `df` to `dof` to accomodate that change.
=> Update df to dof to accomodate StatsBase change

src/glmfit.jl
Using memory profiling I found that memory was being allocated in a convenience function that was called in only one place.
=> Eliminate memory allocation for weights adjustments

src/GLM.jl, src/linpred.jl, src/lm.jl
Introduce `fit!` and create `LinearModel` instance before fitting of the linear model.
Use Cholesky by default.
These changes are motivated by an attempt to extend `GLM.jl` to other array types and they shouldn't have an impact on normal usage of the package.
I think it was cumbersome to construct the correct `LmResp` and `LinPred` data types without constructing the instances which the old version of `fit` required. Here I instead instantiate the types, create the `LinearModel` and call `fit!`.
The change to using Cholesky is not strictly necessary but I think that a Cholesky is implemented slightly more than the QR for other matrix types. It is also much faster to use Cholesky and my view is that the error due to numerical precision loss are insignificant relative to the statistical …
=> Make linear model easier to extend to new array types.

README.md
Edit README to point to the non-deprecated function.
=> "df_residual" -> "dof_residual" in README

REQUIRE, src/glmfit.jl
This PR uses the newly added ConvergenceException in StatsBase to indicate to the user that a fit operation failed to converge.
=> Uses ConvergenceException

README.md, src/lm.jl, test/runtests.jl
Adds basic support for confidence intervals in predict() (see https://github.com/JuliaStats/GLM.jl/issues/101)
I have so far only added to the `lm()` function, but it should be fairly easy to transfor to the `glm()` method. Also, the `predict` call is through `DataFrames`, but I have not touched that package, so it only works inside the module (I use Atom’s ability to set the working module). Also, it is not extensively tested. Oh, and because the intervals return a `Matrix`, this makes the `predict` function not be type stable, so some thought is needed here.
But it is something to build upon.
A quick example (notice I have to jump through some hoops because I bypass DataFrames):
```julia
using DataFrames, RCall
a = randn(100); b = randn(100); c = a .+ b .+ 0.8randn(100);
df = …
```
=> confidence intervals in predict()

README.md, doc/index.rst
Remove list of extractors which are documented in StatsBase (the
docstrings where out of sync for coeftable).
Remove outdated references in README and add new badges.
----
The docs don't seem to be used anywhere so it doesn't really matter. At some point we should move all documentation from README.md to a proper Documenter manual (https://github.com/JuliaStats/GLM.jl/pull/138 is a good step toward that goal).
=> Doc and README.md fixes

.travis.yml, src/glmtools.jl, test/runtests.jl
See https://github.com/dmbates/MixedModels.jl/issues/92 for an example of what can happen if you don't clamp the values on the mean scale to (0,1)
If μ, the value of the inverse link applied to the linear predictor, rounds down to zero or, more commonly, rounds up to one, then the `glmvar` value is zero, resulting in a division by zero.  @andreasnoack contributed special method for `glmvar` the helps with this problem if the inverse link function is "odd" (actually f(-x) == 1 - f(x)) in this case).  In the most common case of the canonical (Logit) link, the calculation of the glmvar can be and is by-passed.  
This link doesn't have such a nice way of avoiding the numerical problems, as far as I can see.
=> Clamp cloglog inverse link

.gitignore, .travis.yml, REQUIRE, docs/make.jl, docs/mkdocs.yml, docs/src/index.md, perf/glm.jl, src/GLM.jl, src/ftest.jl, src/glmfit.jl, src/glmtools.jl, test/runtests.jl
I am proposing these changes in place of https://github.com/JuliaStats/GLM.jl/pull/190
During the iterations of the IRLS algorithm both the inverse link function and its derivative are evaluated.  Separate evaluations can result in a small amount of repeated evaluation which can be avoided by having both values returned by the method for `inverselink`.
The more important issue is ensuring that the evaluation of the derivative and of the variance function returns a non-zero value, because the derivative appears in the denominator of the working residual and the variance function appears in the denominator of the working weights.
It turns out that this is not a problem for most combinations of distribution and link.  When the link is canonical for the distribution the variance function is …
=> Evaluate inverse link and its derivative simultaneously

src/ftest.jl, test/runtests.jl
Fix a typo in `issubmodel` that lead to unexpected behavior.
The added test can work as a MWE: it fails with the current version of GLM, but passes after the commit.
See #195.
=> Typo in `issubmodel`

README.md, REQUIRE, src/GLM.jl, src/glmfit.jl, src/linpred.jl, src/lm.jl, test/runtests.jl
Tighten type for offset vectors in tests to avoid Missing types
Upper bound StatsModels to 0.2.4
=> Change StatsBase.stderr to StatsBase.stderror and bump StatsBase requirement

REQUIRE, test/runtests.jl
Fix deprecated 2-argument `Formula` constructor in StatsModels.jl v0.2.4
=> use macro to construct formula in test for StatsModels v0.2.4

src/ftest.jl, test/runtests.jl
And uncomment tests (commented out by https://github.com/JuliaStats/GLM.jl/pull/192).
Also avoid using mod as an identifier since it can conflict with Base.mod
=> Fix ftest printing

docs/src/index.md, src/GLM.jl, src/deprecated.jl, src/lm.jl, test/runtests.jl
Use keyword arguments, which are passed through by the DataFrameRegressionModel method.
While we're at it, I wonder whether we should change the API a bit. `interval=:confint` and `interval=:predint` could be changed to `interval=:confidence` and `interval=:prediction`, which are the names used by R (since "int" is redundant with `interval`).
Cc: @mkborregaard
=> Fix predict with confidence intervals

src/linpred.jl, src/lm.jl, test/runtests.jl
This PR fixes the `dof` for `allowrankdeficient` models and also `dof_residual` through the use of `dof`.
=> Using dof approach to proper allowrankdeficient values

src/glmfit.jl
σ² is only returned when `sqr=true`.
Fixes https://github.com/JuliaStats/GLM.jl/issues/283.
=> Fix docstring for dispersion

src/GLM.jl, src/linpred.jl
model_response -> response, import modelmatrix.
These are changes that landed almost a year ago in the StatsBase (JuliaStats/StatsBase.jl#321 and JuliaStats/StatsBase.jl#355).  We currently require a version of StatsBase that has all these changes (I think 0.21 is the earliest, and we're at 0.22).
There's a deprecation of `model_response` in favor of `response` in StatsBase; I didn't add one here because I figured that would cover it but I'm not sure.
=> update statsbase API

docs/src/api.md, src/glmfit.jl
I was unable to find any documentation on how to fit a GLM to data, beyond a few
examples in the docs. I have added a small amount of documentation for how to
use `fit`, and added them to the Documenter markdown. I have also re-iterated
that `glm` is an alias for `fit`, which wasn't clear to me when I first started
using this package.
=> Add basic documentation for `fit` and `glm`

src/glmfit.jl
Some important keyword arguments were not specified for
`fit(GeneralizedLienarModel, ...)`, such as `offset`. This commit copies the
documentation from `GlmResp` to the corresponding keyword arguments of `fit`.
=> Add more documentation for keyword arguments used to fit GLMs

src/glmfit.jl, src/negbinfit.jl, test/runtests.jl
We could take the occasion to rename arguments. Maybe `tolerance` would be better than `convtol`? FWIW [FixedEffectsModels](https://github.com/matthieugomez/FixedEffectModels.jl/blob/c64231417ab5b874317e4e00f1497b09332e0a60/src/reg.jl#L11) and [StatsModels.org](http://www.statsmodels.org/stable/generated/statsmodels.genmod.generalized_linear_model.GLM.fit.html#statsmodels.genmod.generalized_linear_model.GLM.fit) use `tol`, so we could use that too.
BTW, `allowrankdeficient` is still a positional argument, should we make it a keyword? And if so under what name?
=> Rename keyword arguments to follow lower case convention

src/GLM.jl, test/runtests.jl
Currently, we export quite a few functions and types. I think most of them aren't relevant to most users so I'm suggesting that they are no longer exported. In this version, I haven't unexported `canonicallink`, `devresid`, and `linpred` but I think we could consider unexporting them as well. Thoughts?
=> Don't export as much

Project.toml, src/glmfit.jl, src/glmtools.jl, src/linpred.jl, src/negbinfit.jl, test/runtests.jl
This is another attempt at fixing #286. A little explanation of the changes here is probably required. The models are fitted with the iteratively reweighted least squares (IRLS) algorithm which is a version of Newton's method where the Fisher information is used as the Hessian. Each update can be efficiently computed as a weighted least squares problem, i.e. the update becomes
so the two quantities to compute are the weights
and the weighted residuals
where `μᵢ=μ(ηᵢ)` with `ηᵢ=xᵢ'β` being the linear predictor and `μ` the inverse link function. The current approach in GLM.jl has been to compute `μ`, `dμdη`, and `Var(yᵢ)` and then compute the ratios defining the weights and residuals.
This approach fairly frequently runs into problems in the Bernoulli case (`yᵢ` is either zero or one and …
=> RFC: Compute working weights and residuals more carefully to reduce underflow

Project.toml
Let's tag a release to support CategoricalArrays 0.7.
=> Bump version to 1.3.3

Project.toml
This is semi-urgent since StatsFuns didn't have an upper bound on SpecialFunctions in version 0.8 so some users are now experiencing breakages when SpecialFunctions and DiffRules are upgraded but StatsFuns is hold back.
=> Allow for StatsFuns 0.9 and prepare for new bugfix release

src/negbinfit.jl, test/runtests.jl
`negbin` relies on helper function `mle_for_θ` to estimate the parameter θ, but
the stopping criteria `maxIter` and `convTol` were not being passed from
`negbin` to `mle_for_θ`.
=> Pass stopping criteria to mle_for_θ

src/negbinfit.jl
Old PR #302 used `tol`, which no longer exists since #312.
=> Fix passing tolerance to mle_for_θ

Project.toml
No breaking changes as far as I can tell since 1.3.6.
=> bump patch version to 1.3.7

.travis.yml
Specifying both `jobs` and `matrix` no longer works.
=> Fix building documentation on Travis

Project.toml
Not sure why CompatHelper didn't handle this one. Possibly because it's just a test dependency. cc @DilumAluthge
=> Allow version 0.6 of CSV

src/glmtools.jl
links from the documentation were not working for me
=> fixed links to juliastats/distributions.jl

src/glmfit.jl, test/runtests.jl
As per the title. I tried to follow the interface of the `predict` function for linear models. Note that for GLMs `:prediction` intervals do not make sense in general; `:confidence` intervals however do.
R's `predict.glm` does not provide intervals, but it can calculate the standard error of the predictions through the `se.fit` option. The intervals in this PR are calculated based on a Normal approximation and the standard error of the predictions is calculated as in R (through the Delta method).
Fixes #101.
=> Add confidence intervals for GLM predictions

src/linpred.jl, src/lm.jl, test/runtests.jl
We need to reorder rows and columns when using pivoted Cholesky decomposition.
Fixes #409.
=> Fix predict with collinear=true

docs/src/index.md
This part got lost when restructuring docs at https://github.com/JuliaStats/GLM.jl/pull/277.
Fixes https://github.com/JuliaStats/GLM.jl/issues/418.
=> Re-add precision about NegativeBinomialLink to manual

.github/workflows/CI-future.yml, .github/workflows/CI-stable.yml, Project.toml, src/negbinfit.jl, test/runtests.jl
As noted in #433, tests are failing on nightly because of the RNG changes so I've switched from the default RNG to `StableRNG` to ensure stability across versions of Julia.
=> Use StableRNG for testing

src/lm.jl, test/runtests.jl
The previous fix (https://github.com/JuliaStats/GLM.jl/pull/410) handled incorreclty cases where pivoted Cholesky decomposition permutes columns in a non-monotonous way. This is because the inverted permutation has to be used, but that bug isn't visible in simple examples.
Fixes https://github.com/JuliaStats/GLM.jl/issues/431.
=> Fix more `predict` confidence intervals when `dropcollinear=true`

src/lm.jl, test/runtests.jl
`predict` currently gives incorrect intervals when some variables have been dropped due to collinearity. Throw an error instead to
avoid misleading users, until we find a fix.
See https://github.com/JuliaStats/GLM.jl/pull/410#issuecomment-793920775.
=> Throw an error in `predict` with intervals for rank-deficient models

Project.toml, src/GLM.jl, src/ftest.jl, src/linpred.jl, test/runtests.jl
To be used by https://github.com/JuliaStats/StatsModels.jl/pull/225
I am not sure how much sense does `nobs::Float64` make but `Float64` is the return type of `nobs`.
=> Implement fstatistic

docs/src/api.md
We should also mention it in the examples and not just in the API reference, but for now it's better than nothing.
Cc: @OndrejSlamecka
=> Add `ftest` to the manual

.github/workflows/Documenter.yml, docs/Project.toml
Currently deployment doesn't happen because some conditions related to Travis are not fulfilled. Hopefully using a newer version of the action will fix it.
=> Fix manual deployment

Project.toml, src/GLM.jl, src/linpred.jl
Depends on https://github.com/JuliaLang/julia/pull/41640/.
Needs to be adjusted regarding the exact DEV-version number.
=> compat fixes for Julia v1.8

docs/src/api.md, src/ftest.jl, test/runtests.jl
This just replaces the function called `issubmodel` with a method for `StatsModels.isnested` in order to provide support for `StatsModels.lrtest` and other goodies that assume that API.  `issubmodel` is deprecated and otherwise there are no changes to the code.
edit: I have not bumped the version.  I'll open a new PR for that once this is merged.
=> use `StatsModels.isnested` instead of defining new `issubmodel` func

Project.toml
Fixes #463.  Neither 1.6.0 nor 1.6.1 were released so to tag a new release we should use 1.6.0.
Should wait on #462 (hence teh target branch)
=> change version back to 1.6.0 since 1.6.0 was never released

Project.toml, src/glmfit.jl, src/linpred.jl, src/lm.jl, test/runtests.jl
This is an alternative to https://github.com/JuliaStats/GLM.jl/pull/443 as discussed in that PR. I'm converting the inputs to `Vector` since we don't really support anything else even though the structs are parametric. Eventually, we can consider loosening this conversion if we want to support e.g. `CuArrays` but it would have to be a more extensive rewrite to ensure that things work and that no slow paths are hit in important cases so, for now, I think this PR is the best way forward. cc @bkamins
=> Allow for sparse arrays and views

Project.toml, src/lm.jl, test/runtests.jl
This PR fixes the docstring of `predict(::LinearModel, x; interval, level)`, which claimed to return a matrix with 3 columns, whereas it is actually a named tuple with three fields (`prediction`, `lower`, `upper`).
It also fixes the types of the returned `lower` and `upper`. Previously, `prediction` was a vector (IMO, the correct shape), whereas `lower` and `upper` were `N x 1` matrices (IMO, the incorrect shape). Now, all three are vectors.
=> fix predict docstring and remove trailing dim

docs/src/index.md
In the text below we say that it is frequent to use the log link with negative binomial, so it makes sense to mention it here too.
Fixes https://github.com/JuliaStats/GLM.jl/issues/476.
=> Fix mention of canonical link for NegativeBinomial

perf/glm.jl
The perf/glm.jl script was using out-of-date constructions.  This includes updates to recent versions of the Random and StatsModels packages.  It turns out that most of the effort in fitting a large-ish Bernoulli model like this is in the linear algebra.  Using Julia v1.7.0-DEV just switching to MKL saves about 30% of the fitting time on my laptop.
```julia
julia> @time glm(pred, resp, Bernoulli());
4.994811 seconds (46.76 k allocations: 2.052 GiB, 2.71% gc time, 0.44% compilation time)
julia> using MKL
julia> @time glm(pred, resp, Bernoulli());
3.549232 seconds (40 allocations: 2.049 GiB, 2.88% gc time)
```
=> Update the perf script.

docs/src/examples.md, docs/src/index.md, src/GLM.jl
In this PR, to improve the readability of the GLM document, we have:
- exported a few methods like `aic`, `aicc`, `bic`, `dispersion` so that, users can access these methods from `GLM` directly
- added a short description of the methods that can be applied to a fitted model
- added some examples to show how to use these methods
=> Readability improvement

.github/workflows/CI-stable.yml, Project.toml, test/runtests.jl
Currently the minimum version is 1.0, which is old and unsupported and makes development and addition of new features more difficult. I suspect this won't be too controversial.
=> Set minimum Julia version to 1.6

.github/workflows/CI-future.yml, .github/workflows/CI-stable.yml, Project.toml
We will tag 0.7 very soon (~~probably today~~ ahahaha good one...) with changes to `FunctionTerm` that are breaking but do not directly affect anything that GLM itself uses.  This PR should not be merged until 0.7 is tagged and CI can be run to ensure that nothing breaks in GLM, so I'll start this in draft mode and flip it out when it's time to check CI.
Update: 0.7 is now released.  I've added bumped the patch version here and also fixed a bug where we were defining our own `formula` function instead of creating a method for `StatsModels.formula`.
Update to teh update: based on #500, I re-based this on a commit before #339 was merged, targeting a "backport" branch called `v1`.
=> add compat for statsmodels 0.7

.github/workflows/CI-stable.yml, Project.toml, test/runtests.jl
* Set minimum Julia version to 1.6
Currently the minimum version is 1.0, which is old and unsupported and
makes development and addition of new features more difficult.
* Fix nightly CI
In Julia 1.10, at-test_broken will error if the expression doesn't
evaluate to a boolean value, making it consistent with at-test. We
actually can fit the model here; the test passes with prior Julia
versions only because the expression doesn't evaluate to a boolean.
(cherry picked from commit 57669ef89de3588ffdbf757d82fd28d5c71f5177)
=> Set minimum Julia version to 1.6 (#514)

docs/src/api.md, src/deprecated.jl, src/glmfit.jl, src/linpred.jl, src/lm.jl, test/runtests.jl
When looking at https://github.com/JuliaStats/GLM.jl/issues/534 I noticed that `fit!(::LinearModel)` depended on the state of `beta0` stored in the linear predictor. The reason was that the solution stored in `delbeta` was transferred to `beta0` by the `installbeta!` method which updated the current value. This is important for GLMs but not LMs. Furthermore, the operations are so simple to do with broadcasting that I think we should rather just do that. (I think `installbeta!` might predate broadcasting in Julia.)
=> Remove installbeta! and make linear model fit insensitive to beta0 state

Project.toml
There are changes currently on `master` that we have determined are Technically Breaking. Setting the version to 2.0.0-DEV indicates the next version that will be released from master and that we're not yet in the state we want for that release.
=> set version to 2.0.0-DEV

.github/workflows/Documenter.yml
I think this is why there the hosted documentation doesn't have 1.8. Once a documentation build with this has gone through, https://github.com/JuliaStats/GLM.jl/issues/541 will be resolved.
=> [v1] Allow documentation building on push

src/negbinfit.jl, test/runtests.jl
`negbin` with weights is currently broken.
This branch fixes this, so that this works for example: `negbin(F, D, args...; wts=wts)`.
A test case is included.
=> negbin now works with weights.

Project.toml, src/glmfit.jl, src/linpred.jl, test/runtests.jl
Fixes https://github.com/JuliaStats/GLM.jl/issues/509
There was actually already a test of a model affected by this but the reference value was wrong. I checked the value in R. 
@nalimilan how do you feel about `dof` after all these years? After preparing this, I think we might be better of from deprecating `dof` (which would have to happen in `StatsAPI`). I tend to think that it brings more confusion than convenience.
=> Change dof_residual definition to not depend on dispersion parameter

.github/workflows/CI-future.yml
There are too many irrelevant failures on nightly.
=> Test with the pre target instead of nightly

test/runtests.jl
Support was dropped in https://github.com/JuliaStats/GLM.jl/pull/514
=> Remove all branches in runtests.jl associated with unsupported versions of Julia

src/glmfit.jl, test/runtests.jl
The current criterion for backtracking assumes that the deviance computed is finite. Hence, extreme parameter values can cause termination instead of reduction of the step.
Fixes #417
=> Backtrack on non-finite deviance values

src/glmfit.jl, src/glmtools.jl, test/runtests.jl
=> fixed order of return values for `inverselink(<:Link01)`

docs/src/index.md, src/glmfit.jl, src/negbinfit.jl
Minor thing but I think it's nicer to use the default logging machinery for this.
=> Use Julia's standard debug loggin mechanism instead of the custom verbose flag.

src/linpred.jl, test/runtests.jl
When fitting based on a QRPivoted factorization, the tolerance used for determining the rank of R should reflect the size of the matrix of which the QR factorization was computed. Hence, a custom rtol based on that first dimension of X is passed to rank.
For consistency, all rank determinations are not handled via rank_linpred as the LinPred object has all the relevant information.
This issue was revealed by #599
=> Adjust tolerance when computing rank of R matrix
